import { MainLayoutProps } from './MainLayout.props';
import Head from 'next/head';
import classNames from 'classnames';
import styles from '../../../styles/Home.module.css';

const MainLayout = ({ children }: MainLayoutProps): JSX.Element => {
  return (
    <>
      <Head>
        <title>Week 5 - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={classNames(styles.main)}>{children}</main>
    </>
  );
};

export default MainLayout;
