import { MainLayoutProps } from './MainLayout.props';
import Head from 'next/head';
import { Montserrat } from 'next/font/google';
import classNames from 'classnames';
import styles from '@/styles/Home.module.css';
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

const MainLayout = ({ children }: MainLayoutProps): JSX.Element => {
  return (
    <>
      <Head>
        <title>Week 5 - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={classNames(styles.main, montserrat.className)}>{children}</main>
    </>
  );
};

export default MainLayout;
