import Head from 'next/head';
import { Montserrat } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ErrorBlock from '@/components/ErrorBlock/ErrorBlock';
import classNames from 'classnames';
import Item from '@/components/Item/Item';

const montserrat = Montserrat({ subsets: ['latin'] });

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Week 5 - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={classNames(styles.main, montserrat.className)}>
        <ErrorBlock />
        <Item
          item={{
            _id: '5cd99d4bde30eff6ebccfc62',
            height: '',
            race: 'Hobbit',
            gender: 'Female',
            birth: 'TA 2818',
            spouse: 'Marmadoc Brandybuck',
            death: '',
            realm: '',
            hair: '',
            name: 'Adaldrida (Bolger) Brandybuck',
            wikiUrl: 'http://lotr.wikia.com//wiki/Adaldrida_(Bolger)_Brandybuck',
          }}
        />
      </main>
    </>
  );
}
